
export const cats = [
  {
    name: "Alice",
    breed: "Mestiza",
    location: "Refugio A",
    arrivalDate: "10/12/2023",
    description: "Muy juguetona y amigable.",
    image: "alice.jpg",
    urgent: false,
  },
  {
    name: "Aurora",
    breed: "Blanco y negro",
    location: "Refugio B",
    arrivalDate: "20/11/2023",
    description: "Tímida pero cariñosa.",
    image: "aurora.jpg",
    urgent: true,
  },
  {
    name: "Billy",
    breed: "Negro",
    location: "Refugio C",
    arrivalDate: "05/01/2024",
    description: "Ama las caricias.",
    image: "billy.jpg",
    urgent: false,
  },
  {
    name: "BJ",
    breed: "Gris y blanco",
    location: "Refugio D",
    arrivalDate: "12/09/2023",
    description: "Muy tranquilo.",
    image: "bj.jpg",
    urgent: false,
  },
  {
    name: "Boba",
    breed: "Blanco y marrón",
    location: "Refugio E",
    arrivalDate: "18/02/2024",
    description: "Le encanta dormir.",
    image: "boba.jpg",
    urgent: false,
  },
  {
    name: "Bow",
    breed: "Atigrado",
    location: "Refugio F",
    arrivalDate: "25/11/2023",
    description: "Curioso y aventurero.",
    image: "bow.jpg",
    urgent: false,
  },
  {
    name: "Ella",
    breed: "Tricolor",
    location: "Refugio G",
    arrivalDate: "30/10/2023",
    description: "Independiente pero dulce.",
    image: "ella.jpg",
    urgent: false,
  },
  {
    name: "Anakin",
    breed: "Desconocida",
    location: "Miami County, Ohio",
    arrivalDate: "20/07/2024",
    description: "Estaba con su amigo, quien lamentablemente fue electrocutado.",
    image: "anakin.jpg",
    urgent: true,
  },
];